apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: s3bucket-mansong-crossplane
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    region: eu-west-2
