apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: s3bucket-mansong-crossplane
  namespace: s3bucket
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: eu-west-2
    publicAccessBlockConfiguration:
          blockPublicPolicy: true
    accelerateConfiguration:
          status: Enabled
    versioningConfiguration:
          status: Enabled
