apiVersion: database.harness.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: harness-crossplane-db
  namespace: postgres
  annotations:
    crossplane.io/external-name: harness-crossplane-db
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: new
  writeConnectionSecretToRef:
    name: db-conn