apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: postgresvpc
  annotations:
    guide: quickstart
    provider: aws
    vpc: new
spec:
  crossplane:
    version: "v1.8.1"
  dependsOn:
    - provider: crossplane/provider-aws
      version: "v0.27.1"